# ===================================
#  Duplicate Behavior Config
# 
# ATTENTION LE TITRE NE DOIT PAS AVOIR D ESPACE

# Model Class name
modelClass: Waka\Programer\Models\Campagne

name: campagnes
title: waka.utils::lang.global.duplicate_theCampagne
redirect: backend/waka/programer/campagnes/update/

duplication:
    #Les champs dans le tableau relation seront cloné et attaché au nouveau model 
    relationsMany:
        - rule_asks
        - rule_fncs
    # relationsBelongsToMany:
    #   - rule_asks
    #   - rule_fncs
  
    # relationsMorphMany:
    #     rule_asks : 
    #         id: askeable_id
    #     rule_fncs:

    #Les champs dans le tableau transformation auront les valeurs listé ci dessous 
    transformation:
        state: init

    #Les champs qui seront modifié dans le formulaire du popup 
    fields:
        name:
          label: waka.mailer::wakamail.name
          span: auto
        slug:
          label: waka.mailer::wakamail.slug
          preset: name
          sapn: auto
        subject:
          label: Sujet de l'email

        # _keep:
        #   label: Dupliquer dans ce projet
        #   type: checkbox
        #   default: 0

        # project:
        #   label: Choisissez un projet
        #   type: relation
        #   placeholder: -- choisissez un projet --
        #   select: concat(name,' | ' ,code)
        #   trigger:
        #     action: hide
        #     field: _keep
        #     condition: checked



          
    
        





